const express = require('express');
const db = require('./model');
const { auth } = require('express-openid-connect');
const {expressjwt: jwt} = require('express-jwt');
const jwksRsa = require('jwks-rsa');
const jwt_decode = require('jwt-decode');
const {wrap} = require('async-middleware');
const DOMAIN = "millse2-cs493-portfolio.us.auth0.com";

// INITIALIZE ROUTERS
const authentication = express.Router();
const boats = express.Router();
const users = express.Router();

/****************************************************************
 *                                                              *
 *                     LIBRARY MIDDLEWARE                       *
 *                                                              *
****************************************************************/

const authMiddleware = auth({
    authRequired: false,
    auth0Logout: true,
    baseURL: process.env.NODE_ENV === "production" ? "https://millse2-cs493-portfolio.uk.r.appspot.com" : 'http://localhost:3000',
    issuerBaseURL: `https://${DOMAIN}`
});

const checkJwt = jwt({
    secret: jwksRsa.expressJwtSecret({
      cache: true,
      rateLimit: true,
      jwksRequestsPerMinute: 5,
      jwksUri: `https://${DOMAIN}/.well-known/jwks.json`
    }),
  
    // Validate the audience and the issuer.
    issuer: `https://${DOMAIN}/`,
    algorithms: ['RS256']
  });

/****************************************************************
 *                                                              *
 *                  CUSTOM MIDDLEWARE - COMMON                  *
 *                                                              *
****************************************************************/

function getFullBaseUrl(req, id) {
    return `${req.protocol}://${req.get("host")}${req.baseUrl}`;
}

function getEntityFromParams(kind) {
    const middlewareFn = async (req, res, next) => {
        const retrievedEntity = await db.getEntity(kind, req.params.id);
        if (!retrievedEntity) return res.status(404).json({"Error": `No ${kind.toLowerCase()} with this ${kind.toLowerCase()}_id exists.`});
        req.retrievedEntities = retrievedEntity;
        next();
    }
    return middlewareFn;
}

function addSelfLinkToResponse(req, res, next) {
    req.retrievedEntities["self"] = `${getFullBaseUrl(req)}/${req.retrievedEntities.id}`;
    req.dataToSend = req.retrievedEntities;
    return next();
}

/**
 * Returns new copy of given object with added self URL.
 * 
 * @param {object} req: the req object generated by express route
 * @param {string} collection: the name of the collection to use in the URL
 * @param {object} objToModify: the object where the self-link will be added
 * @returns {object} copy of object with added self property
 */
function addSelfLinksToResponseList(req, res, next) {
    for (const retrievedEntity of req.retrievedEntities) {
        retrievedEntity.self = `${getFullBaseUrl(req)}/${retrievedEntity.id}`;
    }

    return next();
}

function getNextLink(req) {
    const cursor = req.retrievedMetaData.cursor;
    return cursor ? `${getFullBaseUrl(req)}?cursor=${cursor}` : undefined;
}

function addMetaData(req, res, next) {
    const nextLink = getNextLink(req);
    req.dataToSend = {
        count: req.retrievedMetaData.count,
        next: nextLink,
        data: req.retrievedEntities
    }
    return next();
}

function sendData(req, res) {
    return res.json(req.dataToSend);
}

function assertCorrectOwner(req, res, next) {
    const owner = req.retrievedEntities.user;
    if (owner !== req.auth.sub) return res.status(403).json({"Error": "The authorized user does not have access to this boat."});
    return next();
}

function assertAcceptJson(req, res, next) {
    if (!req.accepts("json")) {
        return res.status(406).json({"Error": "Requested MIME type is not supported."});
    }
    return next();
}

function assertContentJson(req, res, next) {
    if (! (req.get("Content-type") === "application/json")) {
        return res.status(415).json({"Error": "Request body contains unsupported MIME type."});
    }
    next();
}

function handleValidationError(err, req, res, next) {
    if (! (err instanceof db.EntityValidationError)) return next(err);
    console.error(err);
    res.status(400).json({"Error": "One or more of the request attributes are missing or invalid."});
}

function methodNotAllowed(req, res) {
    return res.status(405).end();
}

/****************************************************************
 *                                                              *
 *              CUSTOM MIDDLEWARE - ROUTER MAINS                *
 *                                                              *
****************************************************************/

// POST
async function mwPostEntity(req, res, next) {
    req.body.user = req.auth.sub;
    try {
        const newBoat = await db.storeNewEntity("Boat", req.body);
        req.retrievedEntities = newBoat;
        res.status(201);
        return next();
    } catch (e) {
        return next(e);
    }
}

// GET
async function mwGetAllEntities(req, res, next) {
    const [usersEntities, cursor, count] = await db.getAllEntities("Boat", req.auth.sub, req.query.cursor);
    req.retrievedEntities = usersEntities;
    req.retrievedMetaData = {cursor, count};

    console.log(cursor);
    res.status(200);
    return next();
}

async function mwGetEntity (req, res, next) {
    res.status(200);
    return next();
}

// PATCH
async function mwPatchEntity(req, res, next) {
    const retrievedEntity = req.retrievedEntities;
    try {
        req.retrievedEntities = await db.updateEntity(retrievedEntity, req.body);
        if (!req.retrievedEntities) {
            return res.status(500).end();
        }
        res.status(200);
        return next();
    } catch (err) {
        return next(err);
    }
}

// PUT
async function mwPutEntity (req, res, next) {
    req.body.user = req.auth.sub;
    const retrievedEntity = req.retrievedEntities;
    try {
        req.retrievedEntities = await db.replaceEntity(retrievedEntity, req.body);
        if (!req.retrievedEntities) {
            return res.status(500).end();
        }
        res.status(200);
        return next();
    } catch (err) {
        return next(err);
    }
}

// DELETE
async function mwDeleteEntity(req, res) {
    const entityToDelete = req.retrievedEntities;
    if (! await db.deleteEntity(entityToDelete)) {
        return res.status(500).end();
    };
    return res.status(204).end();
}

/****************************************************************
 *                                                              *
 *                          ROUTERS                             *
 *                                                              *
****************************************************************/

// AUTHENTICATION
authentication.use(authMiddleware);
authentication.get("/", wrap(async (req, res, next) => {
    if (!req.oidc.isAuthenticated()) {
        return next();         // Use Express static middleware to display login page.
    }
    const decoded = jwt_decode(req.oidc.idToken);
    await db.storeNewEntity("User", {sub: decoded.sub});
    res.status(303).redirect("/user-info");
}));
authentication.get("/user-info", (req, res) => {
    res.json(req.oidc.idToken);
});

// BOATS
boats.route("/")
    .get(checkJwt, wrap(mwGetAllEntities), addSelfLinksToResponseList, addMetaData, sendData)
    .post(assertContentJson, assertAcceptJson, checkJwt, wrap(mwPostEntity), addSelfLinkToResponse, sendData)
    .all(methodNotAllowed);

boats.route("/:id")
    .all(checkJwt, getEntityFromParams("Boat"), assertCorrectOwner)
    .get(assertAcceptJson, wrap(mwGetEntity))
    .patch(assertAcceptJson, assertContentJson, wrap(mwPatchEntity))
    .put(assertAcceptJson, assertContentJson, wrap(mwPutEntity))
    .delete(wrap(mwDeleteEntity))
    .all(addSelfLinkToResponse, sendData);

boats.use(handleValidationError);

// USERS
users.get("/", async (req, res) => {
    const allUsers = await db.getAllEntities("User");
    res.status(200).json(allUsers);
});

/****************************************************************
 *                                                              *
 *                          EXPORTS                             *
 *                                                              *
****************************************************************/
module.exports = {
    authentication,
    boats,
    users,
}