const express = require('express');
const db = require('./model');
const { auth } = require('express-openid-connect');
const {expressjwt: jwt} = require('express-jwt');
const jwksRsa = require('jwks-rsa');
const jwt_decode = require('jwt-decode');
const DOMAIN = "millse2-cs493-portfolio.us.auth0.com";

// INITIALIZE ROUTERS
const authentication = express.Router();
const boats = express.Router();
const users = express.Router();

/****************************************************************
 *                                                              *
 *                         MIDDLEWARE                           *
 *                                                              *
****************************************************************/

// LIBRARY MIDDLEWARE
const authMiddleware = auth({
    authRequired: false,
    auth0Logout: true,
    baseURL: process.env.NODE_ENV === "production" ? "https://millse2-cs493-portfolio.uk.r.appspot.com" : 'http://localhost:3000',
    issuerBaseURL: `https://${DOMAIN}`
});

const checkJwt = jwt({
    secret: jwksRsa.expressJwtSecret({
      cache: true,
      rateLimit: true,
      jwksRequestsPerMinute: 5,
      jwksUri: `https://${DOMAIN}/.well-known/jwks.json`
    }),
  
    // Validate the audience and the issuer.
    issuer: `https://${DOMAIN}/`,
    algorithms: ['RS256']
  });

// CUSTOM MIDDLEWARE
/**
 * Returns new copy of given object with added self URL.
 * 
 * @param {object} req: the req object generated by express route
 * @param {string} collection: the name of the collection to use in the URL
 * @param {object} objToModify: the object where the self-link will be added
 * @returns {object} copy of object with added self property
 */
function addSelfLinkToResponse(req, res) {
    try {
        const retrievedEntity = req.retrievedEntity;
        const selfLink = `${req.protocol}://${req.get("host")}${req.baseUrl}/${retrievedEntity.id}`;
        retrievedEntity.self = selfLink;
        res.json(retrievedEntity);
    } catch (err) {
        console.error(err);
        return false;
    }
}

/****************************************************************
 *                                                              *
 *                          ROUTERS                             *
 *                                                              *
****************************************************************/

// AUTHENTICATION
authentication.use(authMiddleware);
authentication.get("/", async (req, res, next) => {
    if (!req.oidc.isAuthenticated()) {
        return next();         // Use Express static middleware to display login page.
    }
    const decoded = jwt_decode(req.oidc.idToken);
    await db.createEntity("User", {sub: decoded.sub});
    res.status(303).redirect("/user-info");
});
authentication.get("/user-info", (req, res) => {
    res.json(req.oidc.idToken);
});

// BOATS
boats.route("/")
    .get(checkJwt, async (req, res) => {
        // User is authenticated
        const allBoats = await db.getAllEntities("Boat");
        const usersBoats = allBoats.filter(boat => boat.owner === req.auth.sub);
        res.status(200).json(usersBoats);
    })
    // Error handler for boats.get
    .get(async (err, req, res, next) => {
        if (err.name === "UnauthorizedError") {
            // User is unauthenticated
            const allBoats = await db.getAllEntities("Boat");
            const allPublicBoats = allBoats.filter(boat => boat.public);
            res.status(200).json(allPublicBoats);
        } else {
            // Some other error, pass to Express
            console.error(err);
            next(err);
        }
    })
    .post(checkJwt, async (req, res, next) => {
        req.body.user = req.auth.sub;
        const newBoat = await db.createEntity("Boat", req.body);
        req.retrievedEntity = newBoat;
        res.status(201);
        next();
    });

boats.delete("/:boatId", checkJwt, async (req, res) => {
    const boatToDelete = await db.getEntity("Boat", req.params.boatId);
    if (!boatToDelete || boatToDelete.owner !== req.auth.sub) {
        // ID doesn't exist or owner is unauthorized
        res.status(403).end();
        return;
    }
    db.deleteEntity(boatToDelete);
    res.status(204).end();
});

boats.use(addSelfLinkToResponse);

// USERS
users.get("/", async (req, res) => {
    const allUsers = await db.getAllEntities("User");
    res.status(200).json(allUsers);
});

/****************************************************************
 *                                                              *
 *                          EXPORTS                             *
 *                                                              *
****************************************************************/
module.exports = {
    authentication,
    boats,
    users,
}